//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIBDD_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class driver
    {
        public int Guid { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Middlename { get; set; }
        public byte[] Photo { get; set; }
        public string Passport { get; set; }
        public string registration_address { get; set; }
        public string Residentional_adress { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
        public string Place_of_work { get; set; }
        public string Post { get; set; }
        public string Comments { get; set; }
        public string Postcode { get; set; }
    }
}
